# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       xorg-x11-drv-fbdev
Summary:    Xorg X11 fbdev video driver
Version:    0.4.2
Release:    1
Group:      System/X11 Hardware Support
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/archive/individual/driver/xf86-video-fbdev-%{version}.tar.bz2
Source100:  xorg-x11-drv-fbdev.yaml
Requires:   xorg-x11-server-Xorg
BuildRequires:  pkgconfig(xorg-server) >= 1.0.99.901
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(fontsproto)
BuildRequires:  pkgconfig(randrproto)
BuildRequires:  pkgconfig(renderproto)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(inputproto)
BuildRequires:  pkgconfig(videoproto)


%description
%{summary}.




%prep
%setup -q -n xf86-video-fbdev-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%(pkg-config xorg-server --variable=moduledir )/drivers/fbdev_drv.so
%{_mandir}/man4/fbdev.4*
# >> files
# << files


